spring:
  application:
    name: parts-calculator-bot
  main:
    web-application-type: none
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
bot:
  name: ${BOT_NAME:}
  token: ${BOT_TOKEN:}
  creator-id: ${CREATOR_ID:}
  admin-ids:
    - ${CREATOR_ID:}
logging:
  level:
    root: INFO
    com.lucky.bot: INFO
    org.telegram: WARN
